banglakit/awesome-bangla

README.md

Add bijoy2unicode to the list.

Add bijoy2unicode

---

README.md

Added link to repo which has the codes used during the time of this work which resulted from a kaggle competition, followed by a technical paper.

Request to add Numta Digit Classification codes and paper 

---

README.md

Bengali Handwritten OCR with CNN

added Bengali Handwritten OCR with CNN repo link

---

README.md

I have added two new datasets that published publicly this year.

Added largest bangla handwritten characters dataset and bangla sign language dataset

---

README.md

Hello,
I added Bengali NLP library toolkit repository here. 
Please check and if you think it's mergable please merge.
regards
Sagor

added bengali nlp library toolkit git

---

README.md

Hi @aniruddha-adhikary dada,
I added some open source large bengali datasets link, also updated NLP Tool section.
Please check, if possible please merge.
thanks and regards
Sagor

listing updates for Semantics Lab projects

---

README.md

added links to bangla-tts and news classification repositories

added bangla-tts and news classification repositories

---

README.md

**New Project Submission**
**App name:** Wordgo
Repo or homepage link: https://github.com/monirz/wordgo
Description: A crossed platform desktop (dictionary) application written in Go and QT/QML

Wordgo dictionary added

---

README.md

Added a link of a self crafted Bengli dataset for Female vs Male name dataset in the Copora/Dataset section.

Bengli Female VS Male names dataset for NLP Tasks

---

README.md

This python package is for translating emoji, emoticons into Bengali text for analyzing text data and understanding insights more precisely.

Added Emoji to BN Text package in NLP tool section

---

README.md

Hi,
I added bengali bert-base model link. model was published on huggingface model hub.
Also modified my previous link.
Please check, if possible please merge.
thanks and regards
Sagor

added Bangla BERT Model

---

README.md

Signed-off-by: Shovon <me.shovon668@outlook.com>

Added Borno Keyboard

---

README.md

Added new corpus link "BanglaWriting: A multi-purpose offline Bangla handwriting dataset"

Added new dataset "BanglaWriting: A multi-purpose offline Bangla handwriting dataset"

---

README.md

Hey,
I've been writing a new bangla programming language in rust. Can you add my project to your bangla programming list?
Thanks

Added new bangla programming language project

---

README.md

Use a small dataset to training a bangla word2vec model using tensorflow

Bangla word2vec training pipeline

---

README.md

A Bangla toolkit contains lots of Bangla language models.

Bangla nlp toolkit(sbnltk) added

---

README.md

End to end pipeline for Bangla speech to text conversion

Bangla Speech to Text tool

---

README.md

A synthetic dataset for bangla license plates (generated with GAN + image processing).

:oncoming_automobile: added bangla lp data

---

README.md

Please add the project to awesome bangla

add contextual spell checker

---

README.md

This is a C++ implementation of the Bangla PoS tagging algorithm provided by  Md. Nesarul Hoque and Md. Hanif Seddiqui in the paper “[Bangla Parts-of-Speech Tagging using Bangla Stemmer and Rule based Analyzer](https://ieeexplore.ieee.org/document/7488111)”

Added Bangla POS Tagger (Rule Based)

---

README.md

This tool will help us to create synthetic data for training the Bangla OCR system

Synthetic data generation for Bangla OCR

---

README.md

Disclosure: I made this aforementioned programming language

Added a new bengali programming language pankti
